### ISSUE TITLE
Task list version 2.0

### ISSUE THREAD

**Issue by Jzow** [wansenai/wansen-erp#41]
This issue is a list of functions that need to be improved, which refers to a plan for the development of business functions to be carried out.

1. System management (Basic)
- [ ] User management 
- [ ] Role management 
- [ ] Department management 
- [ ] Menu management 
- [ ] System configuration

2. Retail management (Including data list query and adding/modifying data)
- [ ] Retail outbound
- [ ] Retail returns

3. Purchasing management
- [ ] Purchase order
- [ ] Purchase receipt
- [ ] Purchase returns

4. Sales management
- [ ] Sales order
- [ ] Purchase outbound
- [ ] Sales returns

5. Warehouse management
- [ ] Other warehousing
- [ ] Other outbound
- [ ] Transfer outbound
- [ ] Assembly order
- [ ] Disassembly order

6. Financial management
- [ ] Income statement
- [ ] Expenditure order
- [ ] Receipt
- [ ] Payment order
- [ ] Transfer receipt
- [ ] Advance payment received

7. Report
- [ ] Product inventory report
- [ ] Account statistics report
- [ ] Retail statistics report
- [ ] Procurement statistics report
- [ ] Sales statistics report
- [ ] Receipt details report
- [ ] Outbound details report
- [ ] Transfer details report
- [ ] Receipt summary report
- [ ] Outbound summary report
- [ ] Purchase, sales, and inventory statistics report
- [ ] Customer reconciliation report
- [ ] Supplier reconciliation report

8. Product management
- [ ] Product category
- [ ] Product info
- [ ] Units of measurement and multiple attributes

9. Basic information and data management
- [ ] Supplier information
- [ ] Ccustomer information
- [ ] Member information
- [ ] Warehouse information
- [ ] Manager Management
- [ ] Settlement account

10. Custom plugin (This feature enables users to install customized plugins they want online)
- [ ] Plugin Management

11. GPT3.5 Customized fine-tuning model
 - [ ] Model Repository
 - [ ] Model fine-tuning
 
 This is a long plan, and I will do my best and time to quickly develop it. If you see the plan in front of the screen and are interested in contributing code together, then thank you very much. If you have any questions, please feel free to contact me.
 
**September 23, 2023, Saturday, rainy day**
**Phase II A6 of Xi'an Software R&D Base in Shaanxi, China**

**Comment by yuluo-zy** [comment]
It looks very interesting, I would like to participate as well, can put some modules for me to try out

**Comment by Jzow** [comment]
> It looks very interesting, I would like to participate as well, can put some modules for me to try out

Hi yuluo, you can choose any module you want to do, and project has some templates for your reference, thanks!
